name: Python Selenium Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2
      with:
        chrome-version: 'latest'  # всегда ставим последнюю стабильную версию

    - name: Run tests
      run: |
        pytest -v
