name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Prepare dist folder
      run: |
        mkdir -p dist/assets
        cp index.html dist/
        cp assets/index-BUH56GOL.js dist/assets/
        cp assets/index-Dy9zO9yl.css dist/assets/

    - name: Run tests
      run: pytest -v
