name: Python Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # --- Установка Chrome + ChromeDriver ---
    - name: Set up Chrome & ChromeDriver
      uses: browser-actions/setup-chrome@v3
      with:
        chrome-version: latest  # Можно указать конкретную версию, например '116.0.5845.96'

    - name: Verify Chrome
      run: google-chrome --version

    - name: Run Selenium tests
      run: |
        pytest -v
