name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # --- Установка Chromium и Chromedriver ---
    - name: Install Chromium & Chromedriver
      run: |
        sudo apt update
        sudo apt install -y chromium-browser chromium-chromedriver
        ln -s /usr/bin/chromium-browser /usr/bin/google-chrome || true

    - name: Verify Chromium & Chromedriver
      run: |
        chromium-browser --version
        chromedriver --version

    - name: Run Selenium tests
      run: |
        pytest -v
